name: Build Image
permissions: write-all
on:
  pull_request:
    branches:
    - main
    tags: ["*.*.*"]
    paths-ignore:
    - "**.md"
    - "**.png"
    - "**.jpg"
    - "**.gif"
    
  push:
    branches:
    - main
    tags: ["*.*.*"]
    paths-ignore:
    - "**.md"
    - "**.png"
    - "**.jpg"
    - "**.gif"
    
  workflow_dispatch:
    inputs:
      run_e2e:
        description: 'Force e2e to run'
        required: false
        type: boolean
jobs:
  build-and-push-image:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [linux]
    env:
      PLATFORMS: linux/amd64,linux/arm64
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Login to aliyun Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.USERNAME_ALI }}
          password: ${{ secrets.PASSWORD_ALI }}

      - name: build-image
        run: |
          export TAG="inspur"
          docker buildx build --platform=${{ env.PLATFORMS }} --push -t registry.cn-hangzhou.aliyuncs.com/testwydimage/vox-box:${TAG} .

